tweak

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -33,10 +33,10 @@ jobs:
         continue-on-error: true
         run: |
           ORC_OUTPUT_FILE=./output.json ORC_OUTPUT_FILE_MODE=json xcodebuild -json -project ./build/orc.xcodeproj -scheme orc_dogfood -configuration Debug -hideShellScriptEnvironment
-          if [ `cat output.json | jq '.["synopsis"]["violations"]'` == 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi          test `cat output.json | jq '.["synopsis"]["dies_processed"]'` != 0
-          if [ `cat output.json | jq '.["synopsis"]["dies_skipped"]'` != 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi          test `cat output.json | jq '.["synopsis"]["dies_processed"]'` != 0
-          if [ `cat output.json | jq '.["synopsis"]["unique_symbols"]'` != 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi          test `cat output.json | jq '.["synopsis"]["dies_processed"]'` != 0
-          if [ `cat output.json | jq '.["synopsis"]["object_files_scanned"]'` != 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi          test `cat output.json | jq '.["synopsis"]["dies_processed"]'` != 0
+          if [ `cat output.json | jq '.["synopsis"]["violations"]'` == 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
+          if [ `cat output.json | jq '.["synopsis"]["dies_skipped"]'` != 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
+          if [ `cat output.json | jq '.["synopsis"]["unique_symbols"]'` != 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
+          if [ `cat output.json | jq '.["synopsis"]["object_files_scanned"]'` != 0 ];  then  echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
       - name: 🛠️ orc release
         id: build-orc-release
         continue-on-error: true
