Environment Variable Support (#83)
* Adding `derive_configuration` to allow for config file overrides to come from environment variables

* adding new tests to dogfood

* testing a failure

* better test reporting

* tweak

* tweak

* tweak

* tweak

* improvements to graceful exit logic

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -32,7 +32,13 @@ jobs:
         id: build-orc-orc_dogfood
         continue-on-error: true
         run: |
-          xcodebuild -project ./build/orc.xcodeproj -scheme orc_dogfood -configuration Debug
+          ORC_OUTPUT_FILE=./output.json ORC_OUTPUT_FILE_MODE=json xcodebuild -json -project ./build/orc.xcodeproj -scheme orc_dogfood -configuration Debug -hideShellScriptEnvironment
+          cat output.json
+          echo # newline
+          if [ `cat output.json | jq '.["synopsis"]["violations"]'` == 0 ]; then echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
+          if [ `cat output.json | jq '.["synopsis"]["dies_skipped"]'` != 0 ]; then echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
+          if [ `cat output.json | jq '.["synopsis"]["unique_symbols"]'` != 0 ]; then echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
+          if [ `cat output.json | jq '.["synopsis"]["object_files_scanned"]'` != 0 ]; then echo "SUCCESS"; else echo "FAILURE"; exit 1; fi
       - name: 🛠️ orc release
         id: build-orc-release
         continue-on-error: true
